version: 0.1

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - bin/prebuild.sh $BUILD_TAXONOMY
  build:
    commands:
      - bin/build.sh $BUILD_TAXONOMY
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist