version: 0.1

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - if [ ! -z "$BUILD_TEST" ]; then BUILD_TAXONOMY=1310605,35758; fi
      - bin/prebuild.sh \$BUILD_TAXONOMY
  build:
    commands:
      - if [ ! -z "$BUILD_TEST" ]; then BUILD_TAXONOMY=1310605,35758; fi
      - bin/build.sh \$BUILD_TAXONOMY
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist