version: 0.1

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - [ ! -z "$BUILD_TEST" ] && BUILD_TAXONOMY=1310605,35758;
      - bin/prebuild.sh \$BUILD_TAXONOMY
  build:
    commands:
      - [ ! -z "$BUILD_TEST" ] && BUILD_TAXONOMY=1310605,35758
      - bin/build.sh \$BUILD_TAXONOMY
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist